### ISSUE TITLE
Error Compelling  the package body for pkg_tfa_apex

### ISSUE THREAD

**Issue by georgegaprial** [fuzziebrain/orclapex-tfa-demo#1]
Error at line 24: PLS-00201: identifier 'OOS_UTIL_CRYPTO.HASH_STR' must be declared
Error at line 23: PL/SQL: Statement ignored
Error at line 222: PL/SQL: Statement ignored
Error at line 70: PL/SQL: Statement ignored
Error at line 223: PLS-00201: identifier 'OOS_UTIL_TOTP.VALIDATE_OTP' must be declared
Error at line 70: PLS-00201: identifier 'OOS_UTIL_TOTP.GENERATE_SECRET' must be declared

1. create or replace package body pkg_tfa_apex
2. as
3.   /**
4.    * TODO_Comments

**Comment by georgegaprial** [comment]
Any Help ?!

**Comment by fuzziebrain** [comment]
The documentation highlights the dependency on OOS_UTIL, so please install that first. Please be patient when requesting for help on open source projects such as this one.

**Comment by georgegaprial** [comment]
Thanks dear

**Comment by georgegaprial** [comment]
I have tried to install OOS_UTIL from this link  

https://github.com/OraOpenSource/oos-utils/blob/master/install/oos_utils_install.sql

but it is not working, What should I do next?


And I am getting this Error:
Technical Info (only visible for developers)
is_internal_error: false
original_additional_info: ORA-04067: not executed, package body &quot;GEORGE.OOS_UTIL_CRYPTO&quot; does not exist
ora_sqlcode: -4067
ora_sqlerrm: ORA-04067: not executed, package body "GEORGE.OOS_UTIL_CRYPTO" does not exist ORA-06512: at "APEX_210100.WWV_FLOW_PROCESS_NATIVE", line 56 ORA-06512: at "APEX_210100.WWV_FLOW_CODE_EXEC_PLSQL", line 124 ORA-06512: at "APEX_210100.WWV_FLOW_DYNAMIC_EXEC", line 2387 ORA-06512: at "GEORGE.PKG_TFA_APEX", line 93 ORA-06508: PL/SQL: could not find program unit being called: "GEORGE.OOS_UTIL_CRYPTO" ORA-06512: at "GEORGE.PKG_TFA_APEX", line 23 ORA-06512: at "GEORGE.PKG_TFA_APEX", line 66 ORA-06512: at line 1 ORA-06512: at "SYS.DBMS_SYS_SQL", line 2120 ORA-06512: at "SYS.WWV_DBMS_SQL_APEX_210100", line 682 ORA-06512: at "APEX_210100.WWV_FLOW_DYNAMIC_EXEC", line 2348 ORA-06512: at "APEX_210100.WWV_FLOW_CODE_EXEC_PLSQL", line 96 ORA-06512: at "APEX_210100.WWV_FLOW_CODE_EXEC_PLSQL", line 330 ORA-06512: at "APEX_210100.WWV_FLOW_CODE_EXEC", line 394 ORA-06512: at "APEX_210100.WWV_FLOW_EXEC_LOCAL", line 2880 ORA-06512: at "APEX_210100.WWV_FLOW_EXEC", line 4434 ORA-06512: at "APEX_210100.WWV_FLOW_EXEC", line 4470 ORA-06512: at "APEX_210100.WWV_FLOW_PROCESS_NATIVE", line 35 ORA-06512: at "APEX_210100.WWV_FLOW_PROCESS_NATIVE", line 1116 ORA-06512: at "APEX_210100.WWV_FLOW_PLUGIN", line 2784
component.type: APEX_APPLICATION_PAGE_PROCESS
component.id: 10265392712517725
component.name: createUser
error_backtrace:

**Comment by fuzziebrain** [comment]
Did you follow the instructions here: https://github.com/OraOpenSource/oos-utils/tree/master/install?

And did you install the oos_utils to the schema GEORGE?

**Comment by georgegaprial** [comment]
Whenever I am trying to execute any of these scripts "create_synonyms.sql" OR "grant_to_oos_utils.sql" OR "oos_utils_install.sql"
I am getting this error 

SP2-0738: Restricted command: 
"whenever sqlerror exit sql.sqlcode"
not available
